name: Add contributors
on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'swat-rash/data-structures'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/CONTRIBUTORS.md'
        COMMIT_MESSAGE: 'Github Bot : Updating Contributors'
        AVATAR_SHAPE: 'square'
