name: Welcome
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/welcome-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: >
            👋 @${author}
            
             Thanks for opening your first issue here! Be sure to follow the issue template!
             
             Regards @swat-rash :v:
          FIRST_PR_MERGED: >
            🎉 @${author}
            
            Congrats on merging your first pull request! Happy Contributing!
            
            Regards @swat-rash :v:
